### ISSUE TITLE
Support System instructions for Gemini

### ISSUE THREAD

**Issue by yan-hic** [jxnl/instructor#1035]
As https://ai.google.dev/gemini-api/docs/system-instructions?lang=python#examples, this is supported (in beta as of this post).
However, when logging in DEBUG, I see that instructor has removed (more ignored) the system instructions.

Can this be added ?

**Comment by ivanleomk** [comment]
Hey @yan-hic, the system instructions are set on the client itself. We don't remove the system instructions per-se, they just aren't used in the generate_content method that we are using. 

```
import google.generativeai as genai
import instructor
from pydantic import BaseModel

model = genai.GenerativeModel(
    model_name="gemini-1.5-flash",
    system_instruction="You are a cat. Your name is Neko.",
)

client = instructor.from_gemini(model)


class Profile(BaseModel):
    species: str
    name: str


resp = client.chat.completions.create(
    messages=[{"role": "user", "content": "What is your name and species?"}],
    response_model=Profile,
)

print(resp)
# > species='cat' name='Neko'
```

This is consistent with the Gemini docs where the system instruction and model name are set on the client itself rather than on the `generate_content` method : https://ai.google.dev/gemini-api/docs/system-instructions?lang=python#examples.

Going to just close this for now but feel free to open it if your issue continues.

**Comment by yan-hic** [comment]
So does client instantiation not support logging ?
I am using
```
logging.basicConfig(level=logging.DEBUG, force=True)

client = instructor.from_gemini(
    client=genai.GenerativeModel(
        model_name="models/gemini-1.5-flash-8b-exp-0924",
        system_instruction="I am a cat"),
    mode=instructor.Mode.GEMINI_JSON,
)

````
and was expecting the system instructions in the log to confirm, as it must be sent to the API somehow.

But anyhow your test confirmed it's passed.
Thanks !

**Comment by ivanleomk** [comment]
@yan-hic logging from instructor's side only covers the model.generate_content function since client instantiation happens before instructor is involved.
