### ISSUE TITLE
I am getting this error: Exception has occurred: OpenAIError The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable

### ISSUE THREAD

**Issue by sungkim11** [jxnl/instructor#277]
**Describe the bug**

**To Reproduce**
python version 3.9.18
pip install -U openai
pip install -U instructor

The code:
import os
import instructor
from openai import OpenAI
import enum
from pydantic import BaseModel

client = instructor.patch(OpenAI())

**Expected behavior**
It works

**Screenshots**
Exception has occurred: OpenAIError The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable

**Comment by ivanleomk** [comment]
Hey @sungkim11, this is an error on OpenAI's side because they need an api key in order to execute the requests that you are making.

```python
from openai import OpenAI
client = OpenAI(
    # Defaults to os.environ.get("OPENAI_API_KEY")
    # Otherwise use: api_key="Your_API_Key",
)
```

Source : https://platform.openai.com/docs/libraries

You can either set the value in your terminal ( that you're executing this from ) by running `export OPENAI_API_KEY=<key goes here>` or changing your code as 

```python
client = instructor.patch(OpenAI(api_key=<key goes here>))
```

Hope this answers the question!

**Comment by sungkim11** [comment]
Thanks! that worked.
