### ISSUE TITLE
No matching distribution found for instructor

### ISSUE THREAD

**Issue by xfzhang990** [jxnl/instructor#342]
**Describe the bug**
Not able to install instructor

**To Reproduce**
pip install instructor

**Expected behavior**

**Screenshots**
My python version is 3.11.7
![image](https://github.com/jxnl/instructor/assets/66865475/4d907292-d99a-4ed1-95ca-60a5d2a2e223)

**Comment by xfzhang990** [comment]
Thank you @gao-hongnan , my actual version is 3.8.17.  My bad!

**Comment by xfzhang990** [comment]
BTW, @gao-hongnan  do you know how to update the python version in Jupyterlab? Cause I found my window's python version is 3.11.7, but the Jupyterlab using the 3.8.17.

**Comment by gao-hongnan** [comment]
Hi @xfzhang990, I do not personally use JupyterLab. But your problem will be trickier if you are _not_ using a package manager such as `conda` because then you have to manage the "switching" of python version yourself.

If you are already managing your virtual environments, then I would think you can do something along these lines (I am using linux/unix based so I am basing the windows command off memory):

```bash
python3.11 -m venv my-env
my-env\Scripts\activate
python3.11 -m pip install jupyterlab
```

Then hopefully you can run your usual `jupyterlab` command via this virtual environment.

Reference: [Jupyter notebook is using different Kernel (python 3.8) from my default python version (Python 3.9) in my machine](https://stackoverflow.com/questions/69657281/jupyter-notebook-is-using-different-kernel-python-3-8-from-my-default-python-v)

**Comment by xfzhang990** [comment]
Thank you @gao-hongnan! I have used Anaconda instead, it works now.
