### ISSUE TITLE
Return Tool Id With Parallel Tool Calling

### ISSUE THREAD

**Issue by tarunamasa** [jxnl/instructor#415]
Can then use this to repack the answers to these tools into the next llm response.

https://platform.openai.com/docs/guides/function-calling (e.g.)

**Comment by jxnl** [comment]
This is great. 

Should this be needed for single calls too? 

Would you want to just have a _tool_id attribute? 

Or do you want to set

**Comment by ls-jason-rossiter** [comment]
This was marked as completed but I can't seem to find a way to retrieve the tool calls completion history and their IDs.

When working on the next LLM request I need to add these tool call results back to the messages array:

1. Add the chat competition from the raw response to the messages array, this contains the references to the `tool_calls` describe [here](https://platform.openai.com/docs/guides/function-calling).
2. Retrieve the tool call ID so that each of the tool call results can be added to the messages array referencing the correct tool call ID.

Do you have any recommendations on how to do this? I can't find it in the docs. 

I've also tried using `resp, completion = client.chat.completions.create_with_completion` but the generator does not contain the raw response: https://github.com/jxnl/instructor/blob/main/instructor/process_response.py#L90-L98

**Comment by andrebattagello** [comment]
Any updates or ideas on how to solve this?
I have the same use case as @ls-jason-rossiter, I'm trying to add the tool_call_id to add the tool execution responses to generate an LLM answer, but `response, completion = client.chat.completions.create_with_completion` does not work for Parallel Tool calling
