### ISSUE TITLE
AnthropicVertex support

### ISSUE THREAD

**Issue by dariuszlubomski** [jxnl/instructor#593]
Similar to AnthropicBedrock, AnthropicVertex will by nice to have.

**Comment by gohjiayi** [comment]
To add on as documentation for anyone planning to use Anthropic Claude models using Bedrock or Vertex AI:

I was not able to find much resources explicitly stating that Vertex AI with Anthropic models was supported, because they all fall under the parent anthropic package, which is taken care of by the [Anthropic](https://python.useinstructor.com/integrations/anthropic/) module. You can see that the `instructor.from_anthropic()` method supports `anthropic.Anthropic | anthropic.AnthropicBedrock | anthropic.AnthropicVertex`.

I tried the [Google GenAI](https://python.useinstructor.com/integrations/genai/) module while the [Vertex AI](https://python.useinstructor.com/integrations/vertex/) module has been deprecated, both of which I failed to get it to work.

On the side note, FYI: I am also using Anthropic models on AWS Bedrock and the [Bedrock](https://python.useinstructor.com/integrations/bedrock) module is able to support it.

Sample code snippet below on using Anthropic models with Vertex AI via Instructor:

```
# pip install -U anthropic[vertex] instructor pydantic

from typing import List
from pydantic import BaseModel, Field
from anthropic import AnthropicVertex
import instructor

class ArticleSummary(BaseModel):
    title: str = Field(..., description="Short, descriptive title")
    tags: List[str] = Field(..., description="3–5 topical tags")
    key_points: List[str] = Field(..., description="Bullet points, 2–5 items")

def main():
    client = AnthropicVertex(
        project_id=<YOUR_PROJECT_ID>,
        region=<YOUR_REGION>,
    )

    iclient = instructor.from_anthropic(
        client=client,
        mode=instructor.Mode.ANTHROPIC_JSON,
    )

    # ⬇️ Use create_with_completion to get both parsed object and raw response
    obj, completion = iclient.messages.create_with_completion(
        model="claude-3-5-sonnet-v2@20241022",
        max_tokens=512,
        messages=[{
            "role": "user",
            "content": (
                "Summarize 'urban wildlife and city planning' as JSON with: "
                "title, 3–5 tags, and 3–5 concise key_points."
            ),
        }],
        response_model=ArticleSummary,
    )

    print("Parsed object:", obj)
    print("\nAs JSON:\n", obj.model_dump_json(indent=2))

    # Anthropic-style usage should be here on Vertex too
    # e.g., {'input_tokens': ..., 'output_tokens': ...}
    print("\nToken usage:", getattr(completion, "usage", None))

    # You can also inspect other raw fields if needed:
    # print(completion.model)
    # print(completion.stop_reason)
    # print(completion.content)

if __name__ == "__main__":
    main()
```
