### ISSUE TITLE
general way or tutorial to support any LLM provider

### ISSUE THREAD

**Issue by jtoy** [jxnl/instructor#733]
**Is your feature request related to a problem? Please describe.**
I see it supports many LLM providers, but its unclear to me if we need to code up support for every provider.
For example does it work with groq llama3-70b?

**Describe the solution you'd like**
Can we have a tutorial and or generic interface to show how to make this work for any provider.
This will increase adoption of the library.

**Comment by tom-pham-visus** [comment]
> For example does it work with groq llama3-70b?

As long as that model can produced structured responses, I don't see why not. Have you tried it yourself first?

**Comment by Tedfulk** [comment]
@jtoy Yes they support groq llama3 70b. [groq-example](https://jxnl.github.io/instructor/hub/groq/?h=groq)

**Comment by ivanleomk** [comment]
@jtoy the easiest way to support new libraries is to use the OpenAI Client since that will use the existing codebase's functionality. If not, you can easily support a new inference provider by adding a new implementation of the `Instructor` base class.

Happy to take PRs if you've got any inference provider in mind but closing this issue for now.

**Comment by arreumb** [comment]
I would like to use Cerebras as a provider with Instructor but it is not clear to me how to do it. Would it be possible to have a simple guide on how to extend  Instructor to make it work with a generic provider ?
