### ISSUE TITLE
Support prompt caching in Anthropic

### ISSUE THREAD

**Issue by miretchin** [jxnl/instructor#984]
**Is your feature request related to a problem? Please describe.**
Want to use Anthropic prompt caching, but doing so requires accessing the beta version of the Anthropic client. It appears the Instructor patch doesn't support proxying to that attribute.

**Describe the solution you'd like**
Somehow allow client.beta.prompt_caching.messages.create()

**Describe alternatives you've considered**
Don't think there's a workaround.

**Additional context**
https://docs.anthropic.com/en/docs/build-with-claude/prompt-caching

**Comment by miretchin** [comment]
@ivanleomk

**Comment by dogonthehorizon** [comment]
You might try the solution here:
https://github.com/jxnl/instructor/discussions/940#discussioncomment-10547298

I haven't tried it yet myself but looks good in theory

**Comment by ivanleomk** [comment]
Hey @miretchin anthropic prompt caching is currently in beta but here's a guide to how to use it in instructor for now. Once the prompt caching is generally avaliable, we'll work on integrating it so that you can cache both your prompts and tools. 

Here's an article on how to do so : https://python.useinstructor.com/blog/2024/09/14/why-should-i-use-prompt-caching/

But in short, just create the client like this

```
from instructor import Instructor, Mode, patch
from anthropic import Anthropic
from pydantic import BaseModel


client = Instructor(
    client=Anthropic(),
    create=patch(
        create=Anthropic().beta.prompt_caching.messages.create,
        mode=Mode.ANTHROPIC_TOOLS,
    ),
    mode=Mode.ANTHROPIC_TOOLS,
)
```

Once you've done so, it's the same exact normal api as the normal instructor client. You can use the `create_with_completion` method in order to monitor and verify that your prompts are indeed being cached.

```
resp, completion = client.chat.completions.create( 
    model="claude-3-haiku-20240307",
    messages=[
        {
            "role": "user",
            "content": [
                {
                    "type": "text",
                    "text": "<book>" + book + "</book>",
                    "cache_control": {"type": "ephemeral"}, 
                },
                {
                    "type": "text",
                    "text": "Extract a character from the text given above",
                },
            ],
        },
    ],
    response_model=Character,
    max_tokens=1000,
)
assert isinstance(resp, Character)
```

**Comment by ivanleomk** [comment]
Going to close this issue for now in light of the new article
